[build]
  publish = "public"
  command = "npm ci && npm run build"

[build.environment]
  HUGO_VERSION = "0.150.1"
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Broad CSP so Tailwind + daisyUI + Google Fonts + Firebase + (any https CDN) load fine
[[headers]]
  for = "/*"
  [headers.values]
  # keep on ONE line
  Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https:; connect-src 'self' https:; img-src 'self' data: blob: https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' data: https:; frame-src https:;"
